all: padreFigliNipotiConExec

padreFigliNipotiConExec.o: padreFigliNipotiConExec.c
	gcc -Wall -c padreFigliNipotiConExec.c
	
padreFigliNipotiConExec: padreFigliNipotiConExec.o
	gcc -Wall -o padreFigliNipotiConExec padreFigliNipotiConExec.o
