all: padreFigliConSalvataggioPID

padreFigliConSalvataggioPID.o: padreFigliConSalvataggioPID.c
	gcc -Wall -c padreFigliConSalvataggioPID.c
	
padreFigliConSalvataggioPID: padreFigliConSalvataggioPID.o
	gcc -Wall -o padreFigliConSalvataggioPID padreFigliConSalvataggioPID.o
