all: padreFiglioConStatus

padreFiglioConStatus.o: padreFiglioConStatus.c
	gcc -Wall -c padreFiglioConStatus.c
	
padreFiglioConStatus: padreFiglioConStatus.o
	gcc -Wall -o padreFiglioConStatus padreFiglioConStatus.o
