all: selezionaLunghezzaLinea

selezionaLunghezzaLinea.o: selezionaLunghezzaLinea.c
	gcc -Wall -c selezionaLunghezzaLinea.c
	
selezionaLunghezzaLinea: selezionaLunghezzaLinea.o
	gcc -Wall -o selezionaLunghezzaLinea selezionaLunghezzaLinea.o
