all: myGrepConFork-ridStErrorEInput

myGrepConFork-ridStErrorEInput.o: myGrepConFork-ridStErrorEInput.c
	gcc -Wall -c myGrepConFork-ridStErrorEInput.c
	
myGrepConFork-ridStErrorEInput: myGrepConFork-ridStErrorEInput.o
	gcc -Wall -o myGrepConFork-ridStErrorEInput myGrepConFork-ridStErrorEInput.o
