all: padreFigliMultipli

padreFigliMultipli.o: padreFigliMultipli.c
	gcc -Wall -c padreFigliMultipli.c
	
padreFigliMultipli: padreFigliMultipli.o
	gcc -Wall -o padreFigliMultipli padreFigliMultipli.o
