all: myGrepConFork-ridStError

myGrepConFork-ridStError.o: myGrepConFork-ridStError.c
	gcc -Wall -c myGrepConFork-ridStError.c
	
myGrepConFork-ridStError: myGrepConFork-ridStError.o
	gcc -Wall -o myGrepConFork-ridStError myGrepConFork-ridStError.o
